name: Sync pull requests to Jira

# This workflow will be triggered when a new issue is opened
on: 
  pull_request:
    types: [closed]

jobs:
  sync_pull_requests_to_jira:
    name: Sync pull requests to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync GitHub issues to Jira project
        uses: tom-borcin/github-actions/sync_issues_to_jira@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_PROJECT: IDFSYNTEST
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
