name: Push to repository branch

# This workflow will be triggered when a new issue is opened
on: push

jobs:
  push_to_repository_branch:
    name: Push to repository branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Push to repository branch
        uses: tom-borcin/github-actions/push_event@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
