name: Push to repository branch

# This workflow will be triggered when a new issue is opened
on: 
  issue_comment

jobs:
  sync_pull_requests_to_jira:
    name: Push to repository branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Push to repository branch
        uses: tom-borcin/github-actions/sync_issues_to_jira@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_PROJECT: IDFSYNTEST
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
